
service: serverless-api

custom:
  region:
    production: us-east-1
    default: us-east-1

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region.${self:provider.stage}, self:custom.region.default}

package:
  artifact: target/serverless-api-${self:provider.stage}.jar

functions:
  default:
    handler: com.abuob.serverless.Handler
    events:
      - http:
          path: default
          method: get
          cors: true
